package com.sitake.authenticator.models.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Builder;


@Builder
@DynamoDBTable(tableName = "User")
public class User {

    private Long id;
    private String nama;
    private String password;
    private String nik;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public Long getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getNama() {
        return nama;
    }

    @DynamoDBAttribute
    public String getPassword() {
        return password;
    }

    @DynamoDBAttribute
    public String getNik() {
        return nik;
    }

}
